export const data = [
  { id_name: "genesis", name: "Gênesis", chapters: 50, group: "pentateuco" },
  { id_name: "exodo", name: "Êxodo", chapters: 40, group: "pentateuco" },
  { id_name: "levitico", name: "Levítico", chapters: 27, group: "pentateuco" },
  { id_name: "numeros", name: "Números", chapters: 36, group: "pentateuco" },
  { id_name: "deuteronomio", name: "Deuteronômio", chapters: 34, group: "pentateuco" },
  { id_name: "josue", name: "Josué", chapters: 24, group: "at_historicos" },
  { id_name: "juizes", name: "Juízes", chapters: 21, group: "at_historicos" },
  { id_name: "rute", name: "Rute", chapters: 4, group: "at_historicos" },
  { id_name: "1samuel", name: "1 Samuel", chapters: 31, group: "at_historicos" },
  { id_name: "2samuel", name: "2 Samuel", chapters: 24, group: "at_historicos" },
  { id_name: "1reis", name: "1 Reis", chapters: 22, group: "at_historicos" },
  { id_name: "2reis", name: "2 Reis", chapters: 25, group: "at_historicos" },
  { id_name: "1cronicas", name: "1 Crônicas", chapters: 29, group: "at_historicos" },
  { id_name: "2cronicas", name: "2 Crônicas", chapters: 36, group: "at_historicos" },
  { id_name: "esdras", name: "Esdras", chapters: 10, group: "at_historicos" },
  { id_name: "neemias", name: "Neemias", chapters: 13, group: "at_historicos" },
  { id_name: "ester", name: "Ester", chapters: 10, group: "at_historicos" },
  { id_name: "jo", name: "Jó", chapters: 42, group: "poeticos" },
  { id_name: "salmos", name: "Salmos", chapters: 150, group: "poeticos" },
  { id_name: "proverbios", name: "Provérbios", chapters: 31, group: "poeticos" },
  { id_name: "eclesiastes", name: "Eclesiastes", chapters: 12, group: "poeticos" },
  { id_name: "canticos", name: "Cânticos de Salomão", chapters: 8, group: "poeticos" },
  { id_name: "isaias", name: "Isaías", chapters: 66, group: "profetas_maiores" },
  { id_name: "jeremias", name: "Jeremias", chapters: 52, group: "profetas_maiores" },
  { id_name: "lamentacoes", name: "Lamentações", chapters: 5, group: "profetas_maiores" },
  { id_name: "ezequiel", name: "Ezequiel", chapters: 48, group: "profetas_maiores" },
  { id_name: "daniel", name: "Daniel", chapters: 12, group: "profetas_maiores" },
  { id_name: "oseias", name: "Oséias", chapters: 14, group: "profetas_menores" },
  { id_name: "joel", name: "Joel", chapters: 3, group: "profetas_menores" },
  { id_name: "amos", name: "Amós", chapters: 9, group: "profetas_menores" },
  { id_name: "obadias", name: "Obadias", chapters: 1, group: "profetas_menores" },
  { id_name: "jonas", name: "Jonas", chapters: 4, group: "profetas_menores" },
  { id_name: "miqueias", name: "Miquéias", chapters: 7, group: "profetas_menores" },
  { id_name: "naum", name: "Naum", chapters: 3, group: "profetas_menores" },
  { id_name: "habacuque", name: "Habacuque", chapters: 3, group: "profetas_menores" },
  { id_name: "sofonias", name: "Sofonias", chapters: 3, group: "profetas_menores" },
  { id_name: "ageu", name: "Ageu", chapters: 2, group: "profetas_menores" },
  { id_name: "zacarias", name: "Zacarias", chapters: 14, group: "profetas_menores" },
  { id_name: "malaquias", name: "Malaquias", chapters: 4, group: "profetas_menores" },
  { id_name: "mateus", name: "Mateus", chapters: 28, group: "evangelhos" },
  { id_name: "marcos", name: "Marcos", chapters: 16, group: "evangelhos" },
  { id_name: "lucas", name: "Lucas", chapters: 24, group: "evangelhos" },
  { id_name: "joao", name: "João", chapters: 21, group: "evangelhos" },
  { id_name: "atos", name: "Atos dos Apóstolos", chapters: 28, group: "nt_historicos" },
  { id_name: "romanos", name: "Romanos", chapters: 16, group: "cartas_paulo" },
  { id_name: "1corintios", name: "1 Coríntios", chapters: 16, group: "cartas_paulo" },
  { id_name: "2corintios", name: "2 Coríntios", chapters: 13, group: "cartas_paulo" },
  { id_name: "galatas", name: "Gálatas", chapters: 6, group: "cartas_paulo" },
  { id_name: "efesios", name: "Efésios", chapters: 6, group: "cartas_paulo" },
  { id_name: "filipenses", name: "Filipenses", chapters: 4, group: "cartas_paulo" },
  { id_name: "colossenses", name: "Colossenses", chapters: 4, group: "cartas_paulo" },
  { id_name: "1tessalonicenses", name: "1 Tessalonicenses", chapters: 5, group: "cartas_paulo" },
  { id_name: "2tessalonicenses", name: "2 Tessalonicenses", chapters: 3, group: "cartas_paulo" },
  { id_name: "1timoteo", name: "1 Timóteo", chapters: 6, group: "cartas_paulo" },
  { id_name: "2timoteo", name: "2 Timóteo", chapters: 4, group: "cartas_paulo" },
  { id_name: "tito", name: "Tito", chapters: 3, group: "cartas_paulo" },
  { id_name: "filemom", name: "Filemom", chapters: 1, group: "cartas_paulo" },
  { id_name: "hebreus", name: "Hebreus", chapters: 13, group: "outras_epistolas" },
  { id_name: "tiago", name: "Tiago", chapters: 5, group: "outras_epistolas" },
  { id_name: "1pedro", name: "1 Pedro", chapters: 5, group: "outras_epistolas" },
  { id_name: "2pedro", name: "2 Pedro", chapters: 3, group: "outras_epistolas" },
  { id_name: "1joao", name: "1 João", chapters: 5, group: "outras_epistolas" },
  { id_name: "2joao", name: "2 João", chapters: 1, group: "outras_epistolas" },
  { id_name: "3joao", name: "3 João", chapters: 1, group: "outras_epistolas" },
  { id_name: "judas", name: "Judas", chapters: 1, group: "outras_epistolas" },
  { id_name: "apocalipse", name: "Apocalipse", chapters: 22, group: "profecias" }
]

 export const filters = [
    { label: "Pentateuco", group: "pentateuco" },
    { label: "Históricos (A.T)", group: "at_historicos" },
    { label: "Poéticos", group: "poeticos" },
    { label: "Profetas (Maiores)", group: "profetas_maiores" },
    { label: "Profetas (Menores)", group: "profetas_menores" },
    { label: "Evangelhos", group: "evangelhos" },
    { label: "Epístolas de Paulo", group: "cartas_paulo" },
    { label: "Outras Epístolas", group: "outras_epistolas" },
    { label: "Profecias", group: "profecias" },

  ];